export default interface Pedidos {
  IdFam020: number,
  Codemp: string,
  Codpro: string,
  Nompro: string,
  Marcom: number,
  Prevta: number,
  Prevts: number,
  Estpro: string,
  Codusu: string,
  Fecreg: Date,
  Unimed: string,
  Codmon: string,
  Progress: number,
}
